config/routes.rb
Leedshack::Application.routes.draw do

  resources :hackers, :except => [:new, :destroy] do
    collection do
      get :food
      get :source
      post :download
    end
  end
  resources :hacker_sessions, :only => [:create, :destroy]
  resources :teams, :except => [:destroy] do
    member do
      post :join
    end
  end
  resources :categories, :only => [:new, :create]
  resources :microposts, :only => [:create]
  resources :hacks, :as => "submissions", :controller => "submissions", :path_names => { :new => 'submit', :edit => 'change' }, :except => [:destroy] do
    collection do
      get :full_list
    end
  end
  resources :foods, :only => [:new, :create, :show] do
    collection do
      get :orders
    end
  end
  resources :commits do 
    collection do 
     get :committed
     end
  end
  
  root :to => "pages#home"
  match "edit-profile",   :to => "hackers#edit",    :as => "edit_profile" 
  match "food",           :to => "hackers#food",    :as => "edit_food"
  match "source",         :to => "hackers#source",  :as => "source" 
  match "signin",         :to => "hackerSessions#new"
  match "signout",        :to => "hackerSessions#destroy"
  match "signup",         :to => "hackers#new"
  
end

app/models/submission.rb
# == Schema Information
# Schema version: 20110727225942
#
# Table name: submissions
#
#  id                     :integer         not null, primary key
#  name                   :string(255)
#  description            :text
#  url                    :string(255)
#  thumbnail_file_name    :string(255)
#  thumbnail_content_type :string(255)
#  thumbnail_file_size    :integer
#  thumbnail_updated_at   :datetime
#  created_at             :datetime
#  updated_at             :datetime
#  team_id                :integer
#

class Submission < ActiveRecord::Base
  
  belongs_to :team
  belongs_to :hacker
  has_many :hackers, :through => :team
  has_and_belongs_to_many :categories, :join_table => "categories_submissions"
  
  attr_accessible :name, :description, :url, :thumbnail, :team_id, :category_ids
  
  HUMANIZED_ATTRIBUTES = {
    :category_ids => "",
    :team_id => ""
  }
  
  def self.human_attribute_name(attr,options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
  
  has_attached_file :thumbnail, :styles => { :medium => "300x300>",:path => "/public/uploads/", :thumb => "100x100>" }
  validates_attachment_size :thumbnail, :less_than => 1.megabytes
  validates_attachment_content_type :thumbnail, :content_type => ['image/jpeg', 'image/png', 'image/jpg', 'image/gif']
  
  validates :name, :presence => true
  validates :description, :presence => true
  validates :team_id, :presence => {:message => "A team must be selected"}
  validates :category_ids, :length => {:minimum => 1, :message => "At least one category must be selected"} 
  
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  before_filter :require_hacker
  before_filter :require_member, :except => [:new, :create, :index, :full_list]
  before_filter :require_admin, :only => [:full_list]

  def new
    @categories = Category.all
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(params[:submission])
    if @submission.save
      redirect_to submission_path(@submission), :flash => {:success => "Your Hack has been submitted"}
    else
      render :new
    end
  end

  def index
    @teams = current_hacker.teams
  end

  def show
    @submission = Submission.includes(:categories).find_by_id(params[:id])
  end

  def edit
    @submission = Submission.includes(:categories).find_by_id(params[:id])
  end

  def update
    @submission = Submission.find_by_id(params[:id])
    if @submission.update_attributes(params[:submission])
      redirect_to submission_path(@submission)
    else
      render(:edit)
    end
  end

  def full_list
    @submissions = Submission.includes(:categories, :team).all
  end

private

  def require_member
    submission = Submission.find_by_id(params[:id])
    unless current_hacker.teams.to_ary.include?(submission.team) || current_hacker.admin?
      flash[:notice] = "You must be on the team to view/edit this Hack."
      redirect_to root_path
      return false
    end
  end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<%= f.association :team, :collection => current_hacker.teams, :label => "Which of your teams is submitting the hack?", :hint => "Only one person on a team should submit the hack.", :input_html => {:style => "width:300px;"} %>
<%= f.input :name, :label => "Hack Name", :input_html => {:class => "large"} %>
<%= f.input :description, :label => "Hack Description" %>
<%= f.input :url, :hint => "Urls must start with http://", :input_html => {:class => "medium"} %>
<%= f.association :categories, :as => :check_boxes, :label => "Challenges"%>
<%= f.input :thumbnail, :input_html => {:class => "large"}  %>

app/views/submissions/edit.html.erb
<h2>Edit Your Hack</h2>
<p>Some text on explaining the process goes here</p>
<%= simple_form_for @submission, :html => { :multipart => true } do |f|%>
	<%= render "fields", :f => f%>
	<%= f.button :submit, :value => "Edit Hack" %>
<% end %>

app/views/submissions/full_list.html.erb
<h1>All Hacks</h1>

	<table cellpadding="0" cellspacing="0" class="tablesorter" id="myTable">
		<thead>
		<tr><th>Hack Name:</th><th>Hack Team:</th><th>Description:</th></tr>
		</thead>
		<tbody>
	<% if @submissions.any? %>
	<% @submissions.each do |hack| %>
		<tr>
			<td>
				<%=  link_to hack.name, submission_path(hack) %>
			</td>
			<td>
				<%= link_to hack.team.name, team_path(hack.team) %>
			</td>
			<td>
				<%= hack.description %>
			</td>
		</tr>
	<% end %>
	<% end %>
		</tbody>
	</table>

app/views/submissions/index.html.erb
<h2>Hacks your teams have submitted</h2>

<% if @teams.any? %>
	<table cellpadding="0" cellspacing="0" class="tablesorter" id="myTable">
		<thead>
		<tr><th>Hack Name:</th><th>Hack Team:</th><th>Options:</th></tr>
		</thead>
		<tbody>
<% @teams.each do |team| %>
<% if team.submissions.any?%>
<% team.submissions.each do |submission| %>
		<tr><td><%= submission.name%></td><td><%= team.name %></td><td><%= link_to "show", submission_path(submission) %> | <%= link_to "edit", edit_submission_path(submission) %></td></tr>
<% end %>
<% end %>
<% end %>
<% else %>
	<p>You have no submitted hacks. You cannot submit a hack without being in a team.</p>
<% end %>
	</tbody>
</table>

app/views/submissions/new.html.erb
<h2>Submit Your Hack</h2>
<p>It's time to submit your hack to the judges and to the presentation... excited yet?</p>
<% if current_hacker.teams.any? %>
<%= simple_form_for @submission, :html => { :multipart => true } do |f|%>
	<%= render "fields", :f => f%>
	<%= f.button :submit, :value => "Submit Hack" %>
<% end %>
<% else %>
	<div class="fail large png_bg">You must be in a team to submit a hack.</div>
<% end %>

app/views/submissions/show.html.erb
<h2><%= @submission.name %></h2>

	<p><%= @submission.description%></p>
	
	<p>Submitted By: <%= @submission.team.name %></p>
	
	<p>Url: <%= @submission.url%></p>
	
	<p>Thumbnail: <% if !@submission.thumbnail_file_name.nil? %><%= image_tag @submission.thumbnail.url(:medium) %><% end %></p>
	
	<p>Entered in categories:
		<ul>
			<% @submission.categories.each do |category|%>
				<li><%= category.name%></li>
			<% end %>
		</ul>
	</p>
	
	<p><%= link_to "Back to Hacks Page", submissions_path%>