config/routes.rb
Leedshack::Application.routes.draw do

  resources :hackers, :except => [:new, :destroy] do
    collection do
      get :food
      get :source
      post :download
    end
  end
  resources :hacker_sessions, :only => [:create, :destroy]
  resources :teams, :except => [:destroy] do
    member do
      post :join
    end
  end
  resources :categories, :only => [:new, :create]
  resources :microposts, :only => [:create]
  resources :hacks, :as => "submissions", :controller => "submissions", :path_names => { :new => 'submit', :edit => 'change' }, :except => [:destroy] do
    collection do
      get :full_list
    end
  end
  resources :foods, :only => [:new, :create, :show] do
    collection do
      get :orders
    end
  end
  resources :commits do 
    collection do 
     get :committed
     end
  end
  
  root :to => "pages#home"
  match "edit-profile",   :to => "hackers#edit",    :as => "edit_profile" 
  match "food",           :to => "hackers#food",    :as => "edit_food"
  match "source",         :to => "hackers#source",  :as => "source" 
  match "signin",         :to => "hackerSessions#new"
  match "signout",        :to => "hackerSessions#destroy"
  match "signup",         :to => "hackers#new"
  
end

app/views/layouts/_footer.html.erb
<div id="footer">
    <p>&copy; Copyright 2011 Hodgetastic </p>
</div>
<!--  END CEND -->

app/views/layouts/_header.html.erb
<div class="topbar"> 
  <div class="container fixed"> 
    <h3><a class="logo" href="#"> 
     <span>LeedsHack</span> 
    </a></h3> 
    <ul> 
      <li class="active"><%= link_to "My Profile", edit_profile_path %></li> 
	  <li><%= link_to "Source", source_path %></li>
      <li><%= link_to "Add Team", new_team_path %></li> 
      <li><%= link_to "View Teams", teams_path %></li> 
      <li><%= link_to "Submit Hack!", new_submission_path %></li> 
      <li><%= link_to "Your Hacks", submissions_path %></li> 
      <li><%= link_to " Food Order", edit_food_path %></li> 
      <li><a href="#">You have <%= timer %></a></li> 
    </ul> 
  </div> 
</div>

app/views/layouts/_javascripts.html.erb
<%= javascript_include_tag "scripts" %>
<%= javascript_include_tag "jquery.tablesorter.min" %>
<%= javascript_include_tag "facebox" %>
<%= javascript_include_tag "jquery.flot.pack" %>
<!--[if IE]>
  <%= javascript_include_tag "excanvas.pack" %>
<![endif]-->
       
<!--[if IE 6]>
<%= javascript_include_tag "pngfix.pack" %>
<script>
    DD_belatedPNG.fix('.png_bg');
</script>        
<![endif]-->
<%= javascript_include_tag "graphs" %>

app/views/layouts/_sidebar.html.erb
  <!--  START SIDEBAR -->
  <div id="sidebar">
    <h3>My Details</h3>
    <ul>
      <li><%= icon("user_32", "Profile")%><%= link_to "My Profile", edit_profile_path %><br />
          	<p>Logged in as <%= current_hacker.email %><br />
				<%= link_to "Sign Out", signout_path %></p>
      </li>
      <li><%= icon("window_app_list_chart_32", "Source")%><%= link_to "Source", source_path %><br />
          <p></p>
      </li>
    </ul>
    <h3>My Teams</h3>
    <ul>
      <li><%= icon("user_business_add_32", "New Team")%><%= link_to "Add Team", new_team_path %><br />
          <p>Create a new team.</p>
      </li>
      <li class="last"><%= icon("user_business_search_32", "View Team")%><%= link_to "View Teams", teams_path %><br />
          <p>View and edit teams you are in.</p>
      </li>
    </ul>
    <h3>Hacks</h3>
    <ul>
      <li><%= icon("page_table_add_32", "Submit")%><%= link_to "Submit A Hack!", new_submission_path %><br />
          <p>TO THE JUDGES!</p>
      </li>
      <li><%= icon("page_table_chart_32", "Submit")%><%= link_to "Your Hacks", submissions_path %><br />
          <p>What did you send again?.</p>
      </li>
    </ul>
    <h3>Food</h3>
    <ul>
      <li><%= icon("basket_add_32", "Order Food")%><%= link_to "Submit Your Food Order", edit_food_path %><br />
          <p>NOM NOM NOM NOM</p>
      </li>
    </ul>
  </div>
  <!--  end div #sidebar -->
  <!--  END SIDEBAR -->
</div>

app/views/layouts/_stylesheets.html.erb
<% if signed_in? %>
	<%= stylesheet_link_tag "styles", :media => "screen" %>
<% else %>
	<%= stylesheet_link_tag "admin", :media => "screen" %>
<% end %>
<%= stylesheet_link_tag "themes/dark_blue", :media => "screen" %>
<%= stylesheet_link_tag "facebox", :media => "screen" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leeds Hack 2</title>
  <%= render "layouts/javascripts" %>
  <%= csrf_meta_tag %>
<link rel="stylesheet" href="http://twitter.github.com/bootstrap/assets/css/bootstrap-1.0.0.min.css">
</head>
<body>
	
	
	
	<%= render "layouts/header" %>

	<div class="container">
		
	<% flash.each do |key,value|%>
		<div class="<%= key %> canhide png_bg"><%= value %></div>
	<% end %>
	<br />
	<br />
	<br />
	
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
	</div>
	
	

<%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leedshack</title>
  <%= render "layouts/stylesheets" %>
  <%= render "layouts/javascripts" %>
  
  <%= csrf_meta_tag %>
</head>


<body>
	<!-- START ADMIN WRAPPER -->

	<div id="admin_wrapper">
		<h2>Welcome to LeedsHack 2</h2>
				
		<%= yield %>
		
	</div>
	<!-- END ADMIN WRAPPER -->
	
	
<%= debug(params) if Rails.env.development? %>
</body>
</html>